function analysis_cr_trialbytrial_full(data2,trialtypes,filename,cs_no,sampling_rate,starting_trial,window,rerun,sf)

%%%%%%%%
%analysis_cr_trialbytrial_full plots normalized eyeblink traces for visual
%examination by the experimenter and produces a text output of the
%responsivness to each stimulus (US/CS, CS1 only, CS2 only [when needed],
%and CS1+CS2 [when needed].

%INPUT:
%data2: the output from summarize_and_plot saved to analysis file (see
%summarize_and_plot.m)
%trialtypes: trialtypes vector from analysis file (see above)
%cs_no: number of inidivial CSs: enter 1 for 1 CS, 2 for 2 CSs, 3 for 2 CSs
%when the CSs are presented both individually and in combination
%sampling_rate: sampling rate (Hz) set in GUI. Typically, two simultaneous
%recordings requires a sampling rate of 4 kHz and three simultaneous
%recordings requires a sampling rate of 5 kHz.
%starting_trial: the first non-US test trial of the session
%window: the window over which a CS is assessed for threshold crossing
%rerun: 'no' = write over existing analysis file; 'yes' = append existing
%analysis file
%sf: 'no' = suppress figures; 'yes' = do not suppress figures

%OUTPUT
%no returned output
%responses for US/CS, CS1, CS2, and/or CS1+2 are displayed at the end of
%execution as percentage of all valid trials
%all analysis parameters are saved in a file that appends the analysis file
%generated by summarize_and_plot.m (see the file).

%%%%%%%%

if nargin < 6
    starting_trial = 0;
    window = [1.2,1.25];
    rerun = 'no';
    sf = 'no';
elseif nargin == 6 && length(starting_trial) > 1
    starting_trial = starting_trial(end);
    window = [1.2,1.25];
    rerun = 'no';
    sf = 'no';
elseif nargin == 6 && length(starting_trial) == 1
    rerun = 'no';
    window = [1.2,1.25];
    sf = 'no';
end

time = linspace(-1000,1000,sampling_rate*2+1); % time vector for 1 second around the CS onset

uscs = find(trialtypes == 1); % define trials on which the US-CS pair occurred
switch cs_no % define trials on which CSs occurred
    case 0
        cs_1 = [];
        cs_2 = [];
        cs_compound = [];
    case 1
        cs_1 = find(trialtypes == 10);
        cs_2 = [];
        cs_compound = [];
    case 2
        cs_1 = find(trialtypes == 10);
        cs_2 = find(trialtypes == 11);
        cs_compound = [];
    case 3
        cs_1 = find(trialtypes == 10);
        cs_2 = find(trialtypes == 11);
        cs_compound = find(trialtypes == 12);
end

cr_10_vector = zeros(length(uscs),4); % characteristics of CRs that exceed 10% of baseline-US peak range
cr_15_vector = zeros(length(uscs),4); % characteristics of CRs that exceed 15% of baseline-US peak range
cr_20_vector = zeros(length(uscs),4); % characteristics of CRs that exceed 20% of baseline-US peak range 
cr_25_vector = zeros(length(uscs),4); % characteristics of CRs that exceed 15% of baseline-US peak range

all_response_vector = zeros(length(uscs),3); % characteristics of responses from all US_CS trials

cr_peak = zeros(length(uscs),1);
cr_threshold_15 = zeros(length(uscs),1);

number_cr_10 = 0; % number of valid CRs exceeding 10% of the baseline-US peak range
number_cr_15 = 0; % number of valid CRs exceeding 10% of the baseline-US peak range
number_cr_20 = 0; % number of valid CRs exceeding 10% of the baseline-US peak range
number_cr_25 = 0; % number of valid CRs exceeding 10% of the baseline-US peak range
dropped = 0; % number of trials dropped (see below for criteria)

need_new_figure = 1;
uscs_count = 0;

for i = uscs
    uscs_count = uscs_count + 1; % generate 5 x 5 plot of 25 individual trials
    if isequal(sf,'no')
        if mod(uscs_count,25) == 1
            figure
            subplot(5,5,1)
        elseif mod(uscs_count,25) == 0
            subplot(5,5,25)
        else
            subplot(5,5,mod(uscs_count,25))
        end
    end
    
    tempa = find(data2((sampling_rate+1):(sampling_rate*window(2)),2,i+starting_trial)>=0.05,1)+(sampling_rate);
    if ~isempty(tempa) % does the response within the specified window (tempa) exceed the minimum threshold criterion for onset described by the equation in tempa?
        all_response_vector(i,1) = tempa;
    else
        all_response_vector(i,1) = NaN;
    end
    [z,k] = max(data2((sampling_rate*window(1)+1):(sampling_rate*window(2)),2,i+starting_trial));
    if ~isempty(z) && ~isempty(k) % is there a maximum response?
        all_response_vector(i,2) = k + sampling_rate*window(1); % report time of maximum
        all_response_vector(i,3) = z; % report size of maximum (normalized)
    else
        all_response_vector(i,2) = NaN;
        all_response_vector(i,3) = NaN;
    end
    
    if isequal(sf,'no') % plot trial
        plot(time,data2(:,2,i+starting_trial))
        axis tight
        hold on
        plot([0,0],[-0.5,1],'--g')
        plot([280,280],[-0.5,1],'--g')
        plot([250,250],[-0.5,1],'--k')
        plot([0,300],[0.1,0.1],'--r')
        plot([0,300],[0.15,0.15],'--m')
        title(['i = ',num2str(i)]);
    end
    [cr_peak_y, cr_peak_x] = max(data2((sampling_rate*window(1)+1):(sampling_rate*window(2)),2,i+starting_trial)); % compute maximum of CR

    cr_peak(i,1) = time(cr_peak_x+(sampling_rate*window(1))); % time of maximum
    cr_peak(i,2) = cr_peak_y; % size of maximum
    
     if data2(.95*sampling_rate,2,i+starting_trial) >= 0.05 || data2(sampling_rate*(window(1)-0.01),2,i+starting_trial)<=-0.05
        title(['i = ',num2str(i),' dropped!']); % if premature onset according to window described, drop trial
        dropped = dropped + 1;
    else
        if ~isempty(find(data2((sampling_rate*window(1)+1):(sampling_rate*window(2)),2,i+starting_trial) >= 0.10, 1))
            number_cr_10 = number_cr_10 + 1; % if exceeds 10% of baseline-US peak, count trial
            cr_10_vector(i,1) = 1; % indicate counted trial
            cr_10_vector(i,2) = find(data2((sampling_rate+1):(sampling_rate*window(2)),2,i+starting_trial >= 0.05),1) + sampling_rate; %indicate response onset
            [y,j] = max(data2((sampling_rate*window(1)+1):(sampling_rate*window(2)),2,i+starting_trial));
            cr_10_vector(i,4) = j + sampling_rate*window(1); %indicate response peak time
            cr_10_vector(i,3) = y; %indicate response peak time
            title(['i = ',num2str(i),' CR10!']); % indicate counted trial at 10% threshold
        else
            cr_10_vector(i,:) = [NaN, NaN, NaN, NaN];
        end
           % same as 10%, but with 15% baseline-US peak criterion
        if ~isempty(find(data2((sampling_rate*window(1)+1):(sampling_rate*window(2)),2,i+starting_trial) >= 0.15, 1))
            number_cr_15 = number_cr_15 + 1;
            cr_15_vector(i,1) = 1;
            index = find(data2((sampling_rate+1):(sampling_rate*window(2)),2,i+starting_trial) >= 0.05, 1);
            cr_threshold_15(i) = time(index+(sampling_rate*window(1)));
            text(time(index+sampling_rate*window(1)-750),data2(index+sampling_rate*window(1),2,i+starting_trial),'\rightarrow');
            cr_15_vector(i,2) = find(data2((sampling_rate+1):(sampling_rate*window(2)),2,i+starting_trial >= 0.05),1) + sampling_rate;
            [y,j] = max(data2((sampling_rate*window(1)+1):(sampling_rate*window(2)),2,i+starting_trial));
            cr_15_vector(i,4) = j + sampling_rate*window(1);
            cr_15_vector(i,3) = y;
            title(['i = ',num2str(i),' CR15!']);
        else
            cr_15_vector(i,:) = [NaN,NaN,NaN,NaN];
        end
            % same as 10%, but with 20% baseline-US peak criterion
        if ~isempty(find(data2((sampling_rate*window(1)+1):(sampling_rate*window(2)),2,i+starting_trial) >= 0.20, 1))
            number_cr_20 = number_cr_20 + 1;
            cr_20_vector(i,1) = 1;
            cr_20_vector(i,2) = find(data2((sampling_rate+1):(sampling_rate*window(2)),2,i+starting_trial >= 0.05),1) + sampling_rate;
            [y,j] = max(data2((sampling_rate*window(1)+1):(sampling_rate*window(2)),2,i+starting_trial));
            cr_20_vector(i,4) = j + sampling_rate*window(1);
            cr_20_vector(i,3) = y;
            title(['i = ',num2str(i),' CR20!']);
        end
        % same as 10%, but with 25% baseline-US peak criterion
        if ~isempty(find(data2((sampling_rate*window(1)+1):(sampling_rate*window(2)),2,i+starting_trial) >= 0.25, 1))
            number_cr_25 = number_cr_25 + 1;
            cr_25_vector(i,1) = 1;
            cr_25_vector(i,2) = find(data2((sampling_rate+1):(sampling_rate*window(2)),2,i+starting_trial >= 0.05),1) + sampling_rate;
            [y,j] = max(data2((sampling_rate*window(1)+1):(sampling_rate*window(2)),2,i+starting_trial));
            cr_25_vector(i,4) = j + sampling_rate*window(1)+1;
            cr_25_vector(i,3) = y;
            title(['i = ',num2str(i),' CR25!']);
        end
    end
    hold off
end

disp(filename)
disp(['CR-10 is ', num2str(100*number_cr_10/(length(uscs)-dropped)),'%.']) % report rate of trials meeting 10% criterion
disp(['CR-15 is ',num2str(100*number_cr_15/(length(uscs)-dropped)),'%.']) % report rate of trials meeting 15% criterion
disp(['CR-20 is ',num2str(100*number_cr_20/(length(uscs)-dropped)),'%.']) % report rate of trials meeting 20% criterion
disp(['CR-25 is ',num2str(100*number_cr_25/(length(uscs)-dropped)),'%.']) % report rate of trials meeting 25% criterion
disp(['Dropped: ',num2str(dropped)])

% compute blocks of trials for mean/peak analysis of CS-only conditioned
% responses

% similar method to US-CS trials

cs = sort([cs_1,cs_2,cs_compound]);
first_last = [];
if ~isempty(cs)
    first_last(1,1:2) = [1,cs(1)];
    if length(cs) > 1
        for i = 2:length(cs)
            first_last(i,1:2) = [cs(i-1)+1,cs(i)];
        end
    end
end

cr_only_10_vector = zeros(length([cs_1,cs_2,cs_compound]),1);
cr_only_15_vector = zeros(length([cs_1,cs_2,cs_compound]),1);
cr_only_20_vector = zeros(length([cs_1,cs_2,cs_compound]),1);
cr_only_25_vector = zeros(length([cs_1,cs_2,cs_compound]),1);

cr_only_peak = zeros(length([cs_1,cs_2,cs_compound]),1);
cr_only_threshold_15 = zeros(length([cs_1,cs_2,cs_compound]),1);

number_cr_only_10_1 = 0;
number_cr_only_15_1 = 0;
number_cr_only_20_1 = 0;
number_cr_only_25_1 = 0;
dropped1 = 0;

number_cr_only_10_2 = 0;
number_cr_only_15_2 = 0;
number_cr_only_20_2 = 0;
number_cr_only_25_2 = 0;
dropped2 = 0;

number_cr_only_10_3 = 0;
number_cr_only_15_3 = 0;
number_cr_only_20_3 = 0;
number_cr_only_25_3 = 0;
dropped3 = 0;

data_temp = [];
count = 0;
overall_count = 0;

for j = cs_1
    if isequal(sf,'no')
        if count == 0 || (count ~= 1 && mod(count,25) == 1)
            figure
        end
    end
    
    count = count + 1;
    overall_count = overall_count + 1;
    if mod(count,25) == 0
        subplot(5,5,25)
    else
        subplot(5,5,mod(count,25))
    end
    if isequal(sf,'no')
        plot(time,data2(:,2,j+starting_trial))
        axis tight
        hold on
        plot([0,0],[-0.5,1],'--g')
        plot([280,280],[-0.5,1],'--g')
        plot([250,250],[-0.5,1],'--k')
        plot([0,300],[0.1,0.1],'--r')
        plot([0,300],[0.15,0.15],'--m')
        title(['j = ',num2str(j)]);
    end
    [cr_peak_y, cr_peak_x] = max(data2((sampling_rate*window(1)+1):(sampling_rate*window(2)),2,j+starting_trial));

    cr_only_peak(overall_count,1) = time(cr_peak_x+(sampling_rate*window(1)));
    cr_only_peak(overall_count,2) = cr_peak_y;
    
    if (data2(.95*sampling_rate,2,j+starting_trial) >= 0.05)
        dropped1 = dropped1 + 1;
        title(['j = ',num2str(j),' dropped!']);
    else
        if ~isempty(find(data2((sampling_rate*window(1)+1):(sampling_rate*window(2)),2,j+starting_trial) >= 0.10, 1))
            number_cr_only_10_1 = number_cr_only_10_1 + 1;
            cr_only_10_vector(overall_count) = 1;
            title(['j = ',num2str(j),' CR10!']);
        end
        if ~isempty(find(data2((sampling_rate*window(1)+1):(sampling_rate*window(2)),2,j+starting_trial) >= 0.15, 1))
            number_cr_only_15_1 = number_cr_only_15_1 + 1;
            cr_only_15_vector(overall_count) = 1;
            index = find(data2((sampling_rate*window(1)+1):(sampling_rate*window(2)),2,j+starting_trial) >= 0.15, 1);
            cr_only_threshold_15(overall_count) = time(index+(sampling_rate*window(1)));
            text(time(index+(sampling_rate*window(1))-750),data2(index+(sampling_rate*window(1)),2,j+starting_trial),'\rightarrow');
            title(['j = ',num2str(j),' CR15!']);
        else
            cr_only_threshold_15(overall_count) = NaN;
        end
        if ~isempty(find(data2((sampling_rate*window(1)+1):(sampling_rate*window(2)),2,j+starting_trial) >= 0.20, 1))
            number_cr_only_20_1 = number_cr_only_20_1 + 1;
            cr_only_20_vector(overall_count) = 1;
            title(['j = ',num2str(j),' CR20!']);
        end
        if ~isempty(find(data2((sampling_rate*window(1)+1):(sampling_rate*window(2)),2,j+starting_trial) >= 0.25, 1))
            number_cr_only_25_1 = number_cr_only_25_1 + 1;
            cr_only_25_vector(overall_count) = 1;
            title(['j = ',num2str(j),' CR25!']);
        end
    end
    hold off
    data_temp = [];
end

disp(['CR-1-10 is ',num2str(100*number_cr_only_10_1/(length(cs_1)-dropped1)),'%.'])
disp(['CR-1-15 is ',num2str(100*number_cr_only_15_1/(length(cs_1)-dropped1)),'%.'])
disp(['CR-1-20 is ',num2str(100*number_cr_only_20_1/(length(cs_1)-dropped1)),'%.'])
disp(['CR-1-25 is ',num2str(100*number_cr_only_25_1/(length(cs_1)-dropped1)),'%.'])
disp(['Dropped: ',num2str(dropped1)]);

data_temp = [];
count = 0;

% plot trials

for k = cs_2
    if count == 0 || (count ~= 1 && mod(count,25) == 1)
        figure
    end
    count = count + 1;
    overall_count = overall_count + 1;
    if mod(count,25) == 0
        subplot(5,5,25)
    else
        subplot(5,5,mod(count,25))
    end

    if isequal(sf,'no')
        plot(time,data2(:,2,k+starting_trial))
        axis tight
        hold on
        plot([0,0],[-0.5,1],'--g')
        plot([280,280],[-0.5,1],'--g')
        plot([250,250],[-0.5,1],'--k')
        plot([0,300],[0.1,0.1],'--r')
        plot([0,300],[0.15,0.15],'--m')
        title(['k = ',num2str(k)]);
    end
    [cr_peak_y, cr_peak_x] = max(((data2((sampling_rate*window(1)+1):(sampling_rate*window(2)),2,k+starting_trial))));
    %text(time(cr_peak_x+(sampling_rate*window(1))-750),cr_peak_y,'\rightarrow');
    cr_only_peak(overall_count,1) = time(cr_peak_x+(sampling_rate*window(1)));
    cr_only_peak(overall_count,2) = cr_peak_y;
    if (data2(.95*sampling_rate,2,k+starting_trial) >= 0.05)
        title(['k = ',num2str(k), 'dropped!']);
        dropped2 = dropped2 + 1;
    else
        
        if ~isempty(find(((data2((sampling_rate*window(1)+1):(sampling_rate*window(2)),2,k+starting_trial))) >= 0.10, 1))
            number_cr_only_10_2 = number_cr_only_10_2 + 1;
            cr_only_10_vector(overall_count) = 1;
            title(['k = ',num2str(k),' CR10!']);
        end
        if ~isempty(find(((data2((sampling_rate*window(1)+1):(sampling_rate*window(2)),2,k+starting_trial))) >= 0.15, 1))
            number_cr_only_15_2 = number_cr_only_15_2 + 1;
            cr_only_15_vector(overall_count) = 1;
            index = find(((data2((sampling_rate*window(1)+1):(sampling_rate*window(2)),2,k+starting_trial))) >= 0.15, 1);
            cr_only_threshold_15(overall_count) = time(index+(sampling_rate*window(1)));
            text(time(index+(sampling_rate*window(1))-750),((data2(index+(sampling_rate*window(1)),2,k+starting_trial))),'\rightarrow');
            title(['k = ',num2str(k),' CR15!']);
        else
            cr_only_threshold_15(overall_count) = NaN;
        end
        if ~isempty(find(((data2((sampling_rate*window(1)+1):(sampling_rate*window(2)),2,k+starting_trial))) >= 0.20, 1))
            number_cr_only_20_2 = number_cr_only_20_2 + 1;
            cr_only_20_vector(overall_count) = 1;
            title(['k = ',num2str(k),' CR20!']);
        end
        if ~isempty(find(((data2((sampling_rate*window(1)+1):(sampling_rate*window(2)),2,k+starting_trial))) >= 0.25, 1))
            number_cr_only_25_2 = number_cr_only_25_2 + 1;
            cr_only_25_vector(overall_count) = 1;
            title(['k = ',num2str(k),' CR25!']);
        end
    end
    hold off
    data_temp = [];
end

disp(['CR-2-10 is ',num2str(100*number_cr_only_10_2/(length(cs_2)-dropped2)),'%.'])
disp(['CR-2-15 is ',num2str(100*number_cr_only_15_2/(length(cs_2)-dropped2)),'%.'])
disp(['CR-2-20 is ',num2str(100*number_cr_only_20_2/(length(cs_2)-dropped2)),'%.'])
disp(['CR-2-25 is ',num2str(100*number_cr_only_25_2/(length(cs_2)-dropped2)),'%.'])
disp(['Dropped: ',num2str(dropped2)])

data_temp = [];
count = 0;

for m = cs_compound
    if count == 0 || (count ~= 1 && mod(count,25) == 1)
        figure
    end
    count = count + 1;
    overall_count = overall_count + 1;
    if mod(count,25) == 0
        subplot(5,5,25)
    else
        subplot(5,5,mod(count,25))
    end

    if isequal(sf,'no')
        plot(time,data2(:,2,m+starting_trial))
        axis tight
        hold on
        plot([0,0],[-0.5,1],'--g')
        plot([280,280],[-0.5,1],'--g')
        plot([250,250],[-0.5,1],'--k')
        plot([0,300],[0.1,0.1],'--r')
        plot([0,300],[0.15,0.15],'--m')
        title(['m = ',num2str(m)]);
    end
    [cr_peak_y, cr_peak_x] = max(((data2((sampling_rate*window(1)+1):(sampling_rate*window(2)),2,m+starting_trial))));
    cr_only_peak(overall_count,1) = time(cr_peak_x+(sampling_rate*window(1)));
    cr_only_peak(overall_count,2) = cr_peak_y;
    if (data2(.95*sampling_rate,2,m+starting_trial) >= 0.05)
        title(['m = ',num2str(m), 'dropped!']);
        dropped3 = dropped3 + 1;
    else
        if ~isempty(find((data2((sampling_rate*window(1)+1):(sampling_rate*window(2)),2,m+starting_trial)) >= 0.10, 1))
            number_cr_only_10_3 = number_cr_only_10_3 + 1;
            cr_only_10_vector(overall_count) = 1;
            title(['m = ',num2str(m),' CR10!']);
        end
        if ~isempty(find((data2((sampling_rate*window(1)+1):(sampling_rate*window(2)),2,m+starting_trial)) >= 0.15, 1))
            number_cr_only_15_3 = number_cr_only_15_3 + 1;
            cr_only_15_vector(overall_count) = 1;
            index = find((data2((sampling_rate*window(1)+1):(sampling_rate*window(2)),2,m+starting_trial)) >= 0.15, 1);
            cr_only_threshold_15(overall_count) = time(index+(sampling_rate*window(1)));
            text(time(index+(sampling_rate*window(1))-750),(data2(index+(sampling_rate*window(1)),2,j+starting_trial)),'\rightarrow');
            title(['m = ',num2str(m),' CR15!']);
        else
            cr_only_threshold_15(overall_count) = NaN;
        end
        if ~isempty(find((data2((sampling_rate*window(1)+1):(sampling_rate*window(2)),2,m+starting_trial)) >= 0.20, 1))
            number_cr_only_20_3 = number_cr_only_20_3 + 1;
            cr_only_20_vector(overall_count) = 1;
            title(['m = ',num2str(m),' CR20!']);
        end
        if ~isempty(find((data2((sampling_rate*window(1)+1):(sampling_rate*window(2)),2,m+starting_trial)) >= 0.25, 1))
            number_cr_only_25_3 = number_cr_only_25_3 + 1;
            cr_only_25_vector(overall_count) = 1;
            title(['m = ',num2str(m),' CR25!']);
        end
    end
    hold off
    data_temp = [];
end

disp(['CR-3-10 is ',num2str(100*number_cr_only_10_3/(length(cs_compound)-dropped3)),'%.'])
disp(['CR-3-15 is ',num2str(100*number_cr_only_15_3/(length(cs_compound)-dropped3)),'%.'])
disp(['CR-3-20 is ',num2str(100*number_cr_only_20_3/(length(cs_compound)-dropped3)),'%.'])
disp(['CR-3-25 is ',num2str(100*number_cr_only_25_3/(length(cs_compound)-dropped3)),'%.'])
disp(['Dropped: ',num2str(dropped3)])

% write over filename_analyzed.mat generated by summarize_and_plot.m

filename = [filename(1:end-4),'_analyzed.mat'];
if isequal(rerun, 'no')
    eval(['save ', filename, ' cr_10_vector cr_only_10_vector cr_15_vector cr_only_15_vector cr_20_vector cr_only_20_vector cr_25_vector cr_only_25_vector cr_peak cr_only_peak cr_threshold_15 cr_only_threshold_15 number_cr_10 number_cr_only_10_1 number_cr_only_10_2 number_cr_only_10_3 number_cr_15 number_cr_only_15_1 number_cr_only_15_2 number_cr_only_15_3 number_cr_20 number_cr_only_20_1 number_cr_only_20_2 number_cr_only_20_3 number_cr_25 number_cr_only_25_1 number_cr_only_25_2 number_cr_only_25_3 dropped dropped1 dropped2 dropped3 uscs all_response_vector -append'])
elseif isequal(rerun, 'yes')
    eval(['save ', filename, ' cr_10_vector cr_only_10_vector cr_15_vector cr_only_15_vector cr_20_vector cr_only_20_vector cr_25_vector cr_only_25_vector cr_peak cr_only_peak cr_threshold_15 cr_only_threshold_15 number_cr_10 number_cr_only_10_1 number_cr_only_10_2 number_cr_only_10_3 number_cr_15 number_cr_only_15_1 number_cr_only_15_2 number_cr_only_15_3 number_cr_20 number_cr_only_20_1 number_cr_only_20_2 number_cr_only_20_3 number_cr_25 number_cr_only_25_1 number_cr_only_25_2 number_cr_only_25_3 dropped dropped1 dropped2 dropped3 uscs all_response_vector'])
end
